import type { Brain, Department, Skill } from "./types";

export const DEPARTMENT_DEFS: Omit<Department, "executiveId" | "managerId" | "supervisorIds">[] = [
  { id: "strategy", name: "Strategy", code: "STR", purpose: "Objectives, planning, and Owner alignment" },
  { id: "engineering", name: "Engineering", code: "ENG", purpose: "Build, integrate, and ship capabilities" },
  { id: "research", name: "Research", code: "RSH", purpose: "Investigate, synthesize, and evidence" },
  { id: "quality", name: "Quality", code: "QLY", purpose: "Independent QC, testing, and standards" },
  { id: "security", name: "Security", code: "SEC", purpose: "Permissions, red team, and review" },
  { id: "operations", name: "Operations", code: "OPS", purpose: "Queues, runtime, and delivery logistics" },
  { id: "knowledge", name: "Knowledge", code: "KNO", purpose: "Organizational memory and retrieval" },
  { id: "skills", name: "Skills Factory", code: "SKL", purpose: "Create, test, and version skills" },
  { id: "workforce", name: "Workforce", code: "WRK", purpose: "Assignment, training, and performance" },
  { id: "governance", name: "Governance", code: "GOV", purpose: "Constitution, risk, and approvals" },
  { id: "recovery", name: "Recovery", code: "RCV", purpose: "Fault handling and succession" },
  { id: "routing", name: "Brain Routing", code: "RTG", purpose: "Model selection, fallback, and benchmarks" },
];

export const EXEC_TITLES = [
  { title: "Chief Strategy Officer", dept: "strategy" },
  { title: "Chief Technology Officer", dept: "engineering" },
  { title: "Chief Information Security Officer", dept: "security" },
  { title: "Chief Operating Officer", dept: "operations" },
  { title: "Chief Quality Officer", dept: "quality" },
  { title: "Chief Recovery Officer", dept: "recovery" },
  { title: "Chief Knowledge Officer", dept: "knowledge" },
  { title: "Chief People Officer", dept: "workforce" },
] as const;

export const CAPABILITIES = [
  "research",
  "analysis",
  "writing",
  "coding",
  "testing",
  "security-review",
  "planning",
  "data",
  "ops",
  "recovery",
  "coaching",
  "benchmarking",
  "routing",
  "documentation",
  "red-team",
  "integration",
  "performance",
  "qc",
  "skill-design",
  "arbitration",
] as const;

export const GIVEN = [
  "Aisha", "Noah", "Mei", "Omar", "Elena", "Kai", "Priya", "Luca", "Amara", "Soren",
  "Hana", "Diego", "Nia", "Jonas", "Zara", "Mateo", "Ines", "Ravi", "Freya", "Leo",
  "Yara", "Theo", "Sana", "Ivo", "Lila", "Kenji", "Noor", "Erik", "Amina", "Hugo",
  "Sofia", "Jamal", "Iris", "Pavel", "Leila", "Andre", "Mina", "Owen", "Dalia", "Niko",
  "Tara", "Samir", "Clara", "Yusuf", "Anya", "Felix", "Rina", "Kofi", "Vera", "Arjun",
  "Nora", "Ibrahim", "Suki", "Marc", "Aya", "Tomas", "Hanae", "Cole", "Imani", "Rafa",
  "Greta", "Adil", "Pia", "Sean", "Lina", "Boris", "Maya", "Quinn", "Esme", "Hassan",
  "June", "Oren", "Kira", "Nabil", "Wren", "Farid", "Tess", "Omaro", "Sable", "Ilya",
];

export const FAMILY = [
  "Okoye", "Voss", "Nakamura", "Rahman", "Silva", "Berg", "Adeyemi", "Kovacs",
  "Chen", "Alvarez", "Iqbal", "Nilsen", "Mensah", "Petrov", "Sato", "Okafor",
  "Moreau", "Khan", "Lindqvist", "Costa", "Abebe", "Novak", "Park", "Hassan",
  "Dubois", "Patel", "Johansson", "Reyes", "Tanaka", "Osei", "Nowak", "Hughes",
  "Kaur", "Jensen", "Almeida", "Mwangi", "Fischer", "Nair", "Larsen", "Romano",
  "Yilmaz", "Brooks", "Kimura", "Diallo", "Horvath", "Singh", "Keller", "Bautista",
  "Oconnor", "Tran", "Ibrahim", "Weiss", "Nkosi", "Gupta", "Bergstrom", "Castillo",
  "Yamamoto", "Farouk", "Olsen", "Kowalski", "Diaz", "Adebayo", "Srinivasan", "Klein",
  "Mbeki", "Rossi", "Haddad", "Pavlov", "Cho", "Nkrumah", "Bergman", "Santos",
  "Qureshi", "Ionescu", "Abe", "Kelemen", "Molina", "Bakker", "Rahmanov", "Frost",
];

export const BRAIN_SEED: Brain[] = [
  {
    id: "grok-4.5",
    name: "Grok 4.5",
    provider: "xai",
    tier: "flagship",
    capabilities: ["reasoning", "planning", "coding", "research", "qc"],
    available: true,
    latencyMs: 1800,
    cost: 8,
    accuracy: 0.94,
    failRate: 0.02,
    tokensUsed: 0,
    tasks: 0,
    specialty: "Complex reasoning and CEO strategy",
  },
  {
    id: "grok-fast",
    name: "Grok Fast",
    provider: "xai",
    tier: "fast",
    capabilities: ["planning", "writing", "analysis"],
    available: true,
    latencyMs: 420,
    cost: 2,
    accuracy: 0.86,
    failRate: 0.04,
    tokensUsed: 0,
    tasks: 0,
    specialty: "Low-latency structured work",
  },
  {
    id: "local-heuristic",
    name: "Local Heuristic",
    provider: "local",
    tier: "local",
    capabilities: ["ops", "routing", "classification"],
    available: true,
    latencyMs: 8,
    cost: 0,
    accuracy: 0.78,
    failRate: 0.01,
    tokensUsed: 0,
    tasks: 0,
    specialty: "Deterministic local brain — always-on fallback",
  },
  {
    id: "open-reasoner",
    name: "Open Reasoner",
    provider: "open",
    tier: "free",
    capabilities: ["research", "writing", "analysis"],
    available: true,
    latencyMs: 900,
    cost: 0,
    accuracy: 0.8,
    failRate: 0.06,
    tokensUsed: 0,
    tasks: 0,
    specialty: "Free-tier research and drafting",
  },
  {
    id: "cloud-coder",
    name: "Cloud Coder",
    provider: "cloud",
    tier: "fast",
    capabilities: ["coding", "integration", "testing"],
    available: true,
    latencyMs: 700,
    cost: 3,
    accuracy: 0.88,
    failRate: 0.05,
    tokensUsed: 0,
    tasks: 0,
    specialty: "Implementation and tests",
  },
];

export const SKILL_SEED: Omit<Skill, "creatorId" | "reviewerId">[] = [
  {
    id: "sk-research-brief",
    name: "Research Brief",
    version: "1.2.0",
    purpose: "Produce an evidenced research brief from an Owner objective",
    capabilities: ["research", "analysis", "writing"],
    dependencies: [],
    permissions: ["memory.read", "web.none"],
    tests: [
      { name: "structure", status: "pass" },
      { name: "citations-status", status: "pass" },
      { name: "adversarial-claims", status: "pass" },
    ],
    benchmark: { score: 0.91, samples: 40 },
    limitations: ["No live web in sandbox"],
    deploymentStatus: "production",
    rollbackVersion: "1.1.0",
    changeHistory: [],
    successRate: 0.91,
  },
  {
    id: "sk-task-decompose",
    name: "Task Decomposition",
    version: "2.0.1",
    purpose: "Break an objective into department and team tasks with dependencies",
    capabilities: ["planning"],
    dependencies: [],
    permissions: ["org.read"],
    tests: [
      { name: "acyclic-deps", status: "pass" },
      { name: "coverage", status: "pass" },
    ],
    benchmark: { score: 0.95, samples: 80 },
    limitations: ["Requires department catalog"],
    deploymentStatus: "production",
    rollbackVersion: "2.0.0",
    changeHistory: [],
    successRate: 0.95,
  },
  {
    id: "sk-qc-review",
    name: "Independent QC Review",
    version: "1.4.0",
    purpose: "Score work against requirements using a brain independent of the author",
    capabilities: ["qc", "analysis"],
    dependencies: [],
    permissions: ["qc.read"],
    tests: [
      { name: "author-isolation", status: "pass" },
      { name: "false-pass-rate", status: "pass" },
    ],
    benchmark: { score: 0.93, samples: 120 },
    limitations: ["Cannot certify high-risk legal claims"],
    deploymentStatus: "production",
    rollbackVersion: "1.3.2",
    changeHistory: [],
    successRate: 0.93,
  },
  {
    id: "sk-test-suite",
    name: "Verification Suite",
    version: "1.1.0",
    purpose: "Run unit, integration, requirement, and edge-case tests on artifacts",
    capabilities: ["testing"],
    dependencies: ["sk-qc-review"],
    permissions: ["test.run"],
    tests: [
      { name: "gate-coverage", status: "pass" },
      { name: "flaky-detection", status: "pass" },
    ],
    benchmark: { score: 0.9, samples: 60 },
    limitations: ["Stress tests are sampled"],
    deploymentStatus: "production",
    rollbackVersion: null,
    changeHistory: [],
    successRate: 0.9,
  },
  {
    id: "sk-red-team",
    name: "Red Team Probe",
    version: "1.0.3",
    purpose: "Adversarially attempt to break artifacts, skills, and workflows",
    capabilities: ["red-team", "security-review"],
    dependencies: [],
    permissions: ["security.probe"],
    tests: [{ name: "does-not-self-certify", status: "pass" }],
    benchmark: { score: 0.87, samples: 24 },
    limitations: ["Does not touch production systems"],
    deploymentStatus: "production",
    rollbackVersion: "1.0.2",
    changeHistory: [],
    successRate: 0.87,
  },
  {
    id: "sk-recovery",
    name: "Recovery Playbook",
    version: "1.0.0",
    purpose: "Transfer state after worker, supervisor, or brain failure",
    capabilities: ["recovery", "ops"],
    dependencies: [],
    permissions: ["org.write"],
    tests: [
      { name: "state-transfer", status: "pass" },
      { name: "no-duplicate-work", status: "pass" },
    ],
    benchmark: { score: 0.96, samples: 18 },
    limitations: ["Requires last valid checkpoint"],
    deploymentStatus: "production",
    rollbackVersion: null,
    changeHistory: [],
    successRate: 0.96,
  },
  {
    id: "sk-coach",
    name: "Worker Coaching",
    version: "1.0.1",
    purpose: "Diagnose repeated failure and apply a correction plan",
    capabilities: ["coaching"],
    dependencies: [],
    permissions: ["workforce.train"],
    tests: [{ name: "root-cause-required", status: "pass" }],
    benchmark: { score: 0.84, samples: 30 },
    limitations: ["Disablement still requires policy"],
    deploymentStatus: "production",
    rollbackVersion: null,
    changeHistory: [],
    successRate: 0.84,
  },
  {
    id: "sk-routing",
    name: "OmniRoute Selection",
    version: "1.3.0",
    purpose: "Select the smallest sufficient brain given quality, latency, and cost",
    capabilities: ["routing", "benchmarking"],
    dependencies: [],
    permissions: ["brains.route"],
    tests: [
      { name: "fallback-chain", status: "pass" },
      { name: "no-task-reset", status: "pass" },
    ],
    benchmark: { score: 0.92, samples: 200 },
    limitations: ["Respects Owner brain disablements"],
    deploymentStatus: "production",
    rollbackVersion: "1.2.0",
    changeHistory: [],
    successRate: 0.92,
  },
];

export const HIGH_RISK_TERMS = [
  "delete",
  "irreversible",
  "production deploy",
  "production change",
  "financial",
  "payment",
  "wire",
  "legal",
  "lawsuit",
  "credential",
  "secret",
  "kill",
  "shutdown external",
  "public statement",
  "security-critical",
];

export const MEDIUM_RISK_TERMS = [
  "deploy",
  "external",
  "customer",
  "policy",
  "permission",
  "reorganize",
  "disable worker",
];
