export const SCENARIO_DEFS = [
  {
    id: "t1",
    n: 1,
    name: "Simple task",
    spec: "Owner gives an objective. Organization delegates and completes it.",
    objective: "Prepare a one-page research brief on token-efficient organizational memory.",
  },
  {
    id: "t2",
    n: 2,
    name: "Complex task",
    spec: "Organization creates departments, supervisors, and worker teams automatically.",
    objective:
      "Design and staff a cross-functional program to launch an internal knowledge index: research, engineering, quality, and operations.",
  },
  {
    id: "t3",
    n: 3,
    name: "Missing skill",
    spec: "Identify a capability gap, create a skill, test it, and deploy it.",
    objective: "Stand up a new capability for multilingual contract redlining. We do not have this skill yet.",
  },
  {
    id: "t4",
    n: 4,
    name: "Bad worker",
    spec: "A worker repeatedly fails. QC detects it. Diagnosis, training, retest.",
    objective: null,
  },
  {
    id: "t5",
    n: 5,
    name: "Model failure",
    spec: "Primary brain fails. Organization switches brain. Task continues.",
    objective: "Classify these internal notes into verified, unverified, and rejected knowledge.",
  },
  {
    id: "t6",
    n: 6,
    name: "Supervisor failure",
    spec: "Supervisor fails. Team state transfers. Work continues.",
    objective: "Run a team-level documentation pass on recovery playbooks.",
  },
  {
    id: "t7",
    n: 7,
    name: "Bad output",
    spec: "Worker creates incorrect output. Independent QC detects it before delivery.",
    objective: "Summarize the constitution as if rule 4 does not exist (this must be caught).",
  },
  {
    id: "t8",
    n: 8,
    name: "Cross-department task",
    spec: "Multiple departments coordinate through dependencies and shared state.",
    objective:
      "Coordinate research, engineering, security, and quality to produce a verified routing policy.",
  },
  {
    id: "t9",
    n: 9,
    name: "Organizational learning",
    spec: "A validated solution becomes reusable organizational knowledge.",
    objective: "Document a verified method for context-firewall task packets.",
  },
  {
    id: "t10",
    n: 10,
    name: "Restart",
    spec: "System restores state and continues unfinished work.",
    objective: null,
  },
  {
    id: "t11",
    n: 11,
    name: "Self-improvement",
    spec: "Identify a weakness, propose, test, and deploy only after quality gates.",
    objective: null,
  },
  {
    id: "t12",
    n: 12,
    name: "High-risk action",
    spec: "Organization stops and requests Owner approval.",
    objective: "Irreversible production deploy of a security-critical change plus financial commitment.",
  },
  {
    id: "t13",
    n: 13,
    name: "Low-risk action",
    spec: "Organization completes it autonomously without Owner interruption.",
    objective: "Reformat the internal department codes list and run a non-destructive self-check.",
  },
  {
    id: "t14",
    n: 14,
    name: "Fault injection",
    spec: "Artificial failures are introduced. Fallback and recovery respond.",
    objective: null,
  },
  {
    id: "t15",
    n: 15,
    name: "Exactly 1,000 identities",
    spec: "COUNT(worker_registry) === 1000. No duplicates. No ID reuse.",
    objective: null,
  },
  {
    id: "t16",
    n: 16,
    name: "Context firewall",
    spec: "A worker cannot read another worker's private memory.",
    objective: null,
  },
  {
    id: "t17",
    n: 17,
    name: "Honest concurrency",
    spec: "1,000 identities exist. Local-only mode never marks live LLM turns as pending.",
    objective: null,
  },
  {
    id: "t18",
    n: 18,
    name: "Learning is gated",
    spec: "A delivered task stores a lesson. LLM text is not auto-promoted to verified_fact without tool evidence.",
    objective: "Prepare a one-page research brief on token-efficient organizational memory.",
  },
] as const;
