/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrainsRouteImport } from './routes/brains'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ImproveRouteImport } from './routes/improve'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkforceRouteImport } from './routes/workforce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainsRoute = BrainsRouteImport.update({
  id: '/brains',
  path: '/brains',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImproveRoute = ImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brains': typeof BrainsRoute
  '/governance': typeof GovernanceRoute
  '/improve': typeof ImproveRoute
  '/memory': typeof MemoryRoute
  '/organization': typeof OrganizationRoute
  '/quality': typeof QualityRoute
  '/scenarios': typeof ScenariosRoute
  '/skills': typeof SkillsRoute
  '/work': typeof WorkRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brains': typeof BrainsRoute
  '/governance': typeof GovernanceRoute
  '/improve': typeof ImproveRoute
  '/memory': typeof MemoryRoute
  '/organization': typeof OrganizationRoute
  '/quality': typeof QualityRoute
  '/scenarios': typeof ScenariosRoute
  '/skills': typeof SkillsRoute
  '/work': typeof WorkRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brains': typeof BrainsRoute
  '/governance': typeof GovernanceRoute
  '/improve': typeof ImproveRoute
  '/memory': typeof MemoryRoute
  '/organization': typeof OrganizationRoute
  '/quality': typeof QualityRoute
  '/scenarios': typeof ScenariosRoute
  '/skills': typeof SkillsRoute
  '/work': typeof WorkRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brains'
    | '/governance'
    | '/improve'
    | '/memory'
    | '/organization'
    | '/quality'
    | '/scenarios'
    | '/skills'
    | '/work'
    | '/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brains'
    | '/governance'
    | '/improve'
    | '/memory'
    | '/organization'
    | '/quality'
    | '/scenarios'
    | '/skills'
    | '/work'
    | '/workforce'
  id:
    | '__root__'
    | '/'
    | '/brains'
    | '/governance'
    | '/improve'
    | '/memory'
    | '/organization'
    | '/quality'
    | '/scenarios'
    | '/skills'
    | '/work'
    | '/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainsRoute: typeof BrainsRoute
  GovernanceRoute: typeof GovernanceRoute
  ImproveRoute: typeof ImproveRoute
  MemoryRoute: typeof MemoryRoute
  OrganizationRoute: typeof OrganizationRoute
  QualityRoute: typeof QualityRoute
  ScenariosRoute: typeof ScenariosRoute
  SkillsRoute: typeof SkillsRoute
  WorkRoute: typeof WorkRoute
  WorkforceRoute: typeof WorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brains': {
      id: '/brains'
      path: '/brains'
      fullPath: '/brains'
      preLoaderRoute: typeof BrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improve': {
      id: '/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof ImproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainsRoute: BrainsRoute,
  GovernanceRoute: GovernanceRoute,
  ImproveRoute: ImproveRoute,
  MemoryRoute: MemoryRoute,
  OrganizationRoute: OrganizationRoute,
  QualityRoute: QualityRoute,
  ScenariosRoute: ScenariosRoute,
  SkillsRoute: SkillsRoute,
  WorkRoute: WorkRoute,
  WorkforceRoute: WorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
